### PR TITLE
Parse excel

### PR DESCRIPTION
**Pull request by jesper-friis**

### CODE REVIEW

**Review by TorgeirUstad — CHANGES_REQUESTED** [review]
`test_parse_xlsx.py`, lines 11-14:
Instead of first `thisdir = Path(__file__).absolute().parent`
and then `downloadUrl=f"file://{thisdir}/test_parse_xlsx.xlsx",`

you could write `thisfile = Path(__file__).absolute()`
and then `downloadUrl=f"file://{thisfile}",`

However, this doesn't quite work either on Windows, cf. `test_application_json.py` in PR #35 in the `oteapi-core` repository.

Also, I have trouble importing DLite here.

**Comment by jesper-friis** [comment]
> you could write thisfile = Path(__file__).absolute() and then downloadUrl=f"file://{thisfile}",

Yes, that is possible, but I want to refer to the .xlsx file instead of the python script itself.

**Comment by francescalb** [comment]
I tried to run the test with pytest locally, but this dit not work:

>           filename = Path("/" + self.download_config.downloadUrl.host + str(filename))
E           TypeError: can only concatenate str (not "NoneType") to str

It might be an error in my installation, but I think we should add proper automatic testing from the start.

**Comment by TorgeirUstad** [comment]
@francescalb 
This was a workaround I included because the CI/CD workflow failed on Linux without it. When I pushed the unit tests in `oteapi-core` it worked in the CI/CD. But Jesper found a problem, and Casper then made an issue (#74) which is still not resolved (waiting for PR #81 to be merged).

The CI/CD run Ubuntu. Could it be that the issue is on Fedora? That would explain why you and Jesper are having problems, while the CI/CD aren't.

**Comment by francescalb** [comment]
> @francescalb This was a workaround I included because the CI/CD workflow failed on Linux without it. When I pushed the unit tests in `oteapi-core` it worked in the CI/CD. But Jesper found a problem, and Casper then made an issue (#74) which is still not resolved (waiting for PR #81 to be merged).
> 
> The CI/CD run Ubuntu. Could it be that the issue is on Fedora? That would explain why you and Jesper are having problems, while the CI/CD aren't.

But there is no automatic CI/CD in this repo?

**Comment by TorgeirUstad** [comment]
Not yet, but there should be!

We could copy (some of) the workflows from `oteapi-core` and adapt them to this repository.

**Comment by francescalb** [comment]
> > > @francescalb This was a workaround I included because the CI/CD workflow failed on Linux without it. When I pushed the unit tests in `oteapi-core` it worked in the CI/CD. But Jesper found a problem, and Casper then made an issue (#74) which is still not resolved (waiting for PR #81 to be merged).
> > > The CI/CD run Ubuntu. Could it be that the issue is on Fedora? That would explain why you and Jesper are having problems, while the CI/CD aren't.
> > 
> > 
> > But there is no automatic CI/CD in this repo?
> 
> My point was that the error message in your comment above is from a file in `oteapi-core`, and there there are CI/CD workflows.

Thank you for the explanation. I was a bit confused.

**Pull request merged**
